import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { AuthRepository } from "../src/auth-repository.js";

test("accounts hash passwords, reject duplicates and invalidate logout tokens", async () => { const folder = mkdtempSync(join(tmpdir(), "project-one-auth-")); const repository = new AuthRepository(join(folder, "alpha.sqlite")); try { const created = await repository.register("usuario_test", "usuario@test.local", "senha-segura"); assert.equal(created.ok, true); if (!created.ok) return; const account = (repository as unknown as { accountBy: (field: "username", value: string) => { passwordHash: string } }).accountBy("username", "usuario_test"); assert.notEqual(account.passwordHash, "senha-segura"); assert.equal((await repository.login("usuario_test", "errada")).ok, false); const login = await repository.login("usuario_test", "senha-segura"); assert.equal(login.ok, true); if (!login.ok) return; assert.equal((await repository.register("usuario_test", "outro@test.local", "senha-segura")).ok, false); assert.equal((await repository.register("outro", "usuario@test.local", "senha-segura")).ok, false); assert.ok(repository.validate(login.session.token)); repository.logout(login.session.token); assert.equal(repository.validate(login.session.token), undefined); } finally { repository.close(); rmSync(folder, { recursive: true, force: true }); } });
test("player state persists inventory, storage, fruit and utility configuration", async () => { const folder = mkdtempSync(join(tmpdir(), "project-one-player-")); const path = join(folder, "alpha.sqlite"); const repository = new AuthRepository(path); let reopened: AuthRepository | undefined; try { const registered = await repository.register("marujo", "marujo@test.local", "senha-segura"); if (!registered.ok) return assert.fail(registered.message); const initial = repository.loadPlayer(registered.session.accountId)!; initial.totalXp = 125; initial.berries = 44; initial.inventory = [{ itemId: "item_gravel", quantity: 3 }]; initial.storage = [{ itemId: "item_soap", quantity: 2 }]; initial.ownedFruitIds = ["fruit_sube_sube"]; initial.activeFruitId = "fruit_sube_sube"; initial.utilitySlots = ["item_potion_small", null]; initial.discovery.items = ["item_gravel"]; repository.savePlayer(registered.session.accountId, initial); repository.close(); reopened = new AuthRepository(path); const saved = reopened.loadPlayer(registered.session.accountId)!; assert.equal(saved.totalXp, 125); assert.equal(saved.berries, 44); assert.deepEqual(saved.storage, initial.storage); assert.equal(saved.activeFruitId, "fruit_sube_sube"); assert.deepEqual(saved.utilitySlots, initial.utilitySlots); } finally { try { repository.close(); } catch {} reopened?.close(); rmSync(folder, { recursive: true, force: true }); } });
