import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { PNG } from "pngjs";
import { ContentRepository, ContentValidationError, type ContentFruit, type ContentItem } from "./content-repository.js";

const json = (response: ServerResponse, status: number, value: unknown) => { response.writeHead(status, { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": "http://localhost:5174", "access-control-allow-methods": "GET,POST,PUT,DELETE,OPTIONS", "access-control-allow-headers": "content-type" }); response.end(JSON.stringify(value)); };
const rawBody = async (request: IncomingMessage, max = 5 * 1024 * 1024) => { const chunks: Buffer[] = []; let length = 0; for await (const chunk of request) { const part = Buffer.from(chunk); length += part.length; if (length > max) throw new ContentValidationError("PNG excede o limite de 5 MB."); chunks.push(part); } return Buffer.concat(chunks); };
const body = async (request: IncomingMessage) => JSON.parse((await rawBody(request)).toString("utf8"));
const metadata = (data: Buffer) => { if (data.length < 24 || !data.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) throw new ContentValidationError("Arquivo não possui assinatura PNG válida."); const png = PNG.sync.read(data, { checkCRC: true }); if (png.width > 2048 || png.height > 2048) throw new ContentValidationError("PNG deve ter no máximo 2048 × 2048 pixels."); let transparent = false; for (let offset = 3; offset < png.data.length; offset += 4) if (png.data[offset] < 255) { transparent = true; break; } if (!transparent) throw new ContentValidationError("Este PNG não possui transparência real."); return { width: png.width, height: png.height, bytes: data.length, alpha: true, transparent: true }; };

export function startAdminApi(repository: ContentRepository, onContentSaved?: () => Promise<void>): void { const saved = async () => { await onContentSaved?.(); return { ok: true, runtimeReloaded: Boolean(onContentSaved) }; }; createServer(async (request, response) => { try { if (request.method === "OPTIONS") return json(response, 204, {}); const url = new URL(request.url ?? "/", "http://localhost"); if (url.pathname === "/admin/content" && request.method === "GET") return json(response, 200, await repository.read());
  if (url.pathname === "/admin/content/items" && request.method === "POST") { await repository.createItem(await body(request) as ContentItem); return json(response, 201, await saved()); }
  if (url.pathname === "/admin/content/fruits" && request.method === "POST") { await repository.createFruit(await body(request) as ContentFruit); return json(response, 201, await saved()); }
  const asset = url.pathname.match(/^\/admin\/content\/assets\/(items|fruits)\/([a-z0-9_]+)$/); if (asset && request.method === "POST") { if (!request.headers["content-type"]?.toLowerCase().startsWith("image/png")) throw new ContentValidationError("Envie somente PNG com MIME image/png."); const data = await rawBody(request), result = metadata(data), destination = repository.assetPath(asset[1] as "items" | "fruits", asset[2]); await mkdir(dirname(destination.filePath), { recursive: true }); await writeFile(destination.filePath, data); return json(response, 201, { ok: true, iconPath: destination.iconPath, metadata: result }); }
  const item = url.pathname.match(/^\/admin\/content\/items\/([a-z0-9_]+)$/); if (item && request.method === "PUT") { await repository.updateItem(item[1], await body(request) as ContentItem); return json(response, 200, await saved()); } if (item && request.method === "DELETE") { await repository.deleteItem(item[1]); return json(response, 200, await saved()); }
  const fruit = url.pathname.match(/^\/admin\/content\/fruits\/([a-z0-9_]+)$/); if (fruit && request.method === "PUT") { await repository.updateFruit(fruit[1], await body(request) as ContentFruit); return json(response, 200, await saved()); } if (fruit && request.method === "DELETE") { await repository.deleteFruit(fruit[1]); return json(response, 200, await saved()); }
  const loot = url.pathname.match(/^\/admin\/content\/loot\/([a-z0-9_]+)$/); if (loot && request.method === "PUT") { await repository.updateLootTable(loot[1], await body(request)); return json(response, 200, await saved()); }
  return json(response, 404, { error: "Not found" });
} catch (error) { return json(response, error instanceof ContentValidationError ? 400 : 500, { error: error instanceof Error ? error.message : "Erro interno" }); } }).listen(8788, "127.0.0.1", () => console.log("Development Content Admin API listening on http://127.0.0.1:8788")); }
