import { randomUUID } from "node:crypto";
import { itemDefinitions, type AuctionListingSnapshot, type AuctionOfferSnapshot, type AuctionSnapshot, type Currency, type ItemId } from "@onepiece/shared";
import type { PlayerDomain } from "./domain.js";
import { auctionFee, type WalletService } from "./economy.js";

const TWO_DAYS = 48 * 60 * 60 * 1000;
type Listing = AuctionListingSnapshot;
type Offer = AuctionOfferSnapshot;
type Result = { ok: true } | { ok: false; reason: string };

/** In-memory marketplace. Listing items and offers are escrowed until settlement. */
export class AuctionService {
  private readonly listings = new Map<string, Listing>();
  private readonly offers = new Map<string, Offer>();
  constructor(private readonly wallets: WalletService, private readonly playerById: (id: string) => PlayerDomain | undefined) {}
  snapshotFor(playerId: string, now = Date.now()): AuctionSnapshot { this.expire(now); const listings = [...this.listings.values()]; return { listings: listings.filter((listing) => listing.status === "ACTIVE"), myListings: listings.filter((listing) => listing.sellerId === playerId), receivedOffers: [...this.offers.values()].filter((offer) => this.listings.get(offer.listingId)?.sellerId === playerId), myOffers: [...this.offers.values()].filter((offer) => offer.buyerId === playerId), feeBps: 1000, expiresInMs: TWO_DAYS }; }
  createListing(seller: PlayerDomain, itemId: ItemId, quantity: number, berriesPrice: number | undefined, rubiesPrice: number | undefined, allowOffers: boolean, now = Date.now()): Result { this.expire(now); const definition = itemDefinitions[itemId]; if (!definition?.tradeable || definition.marketable === false) return { ok: false, reason: "Este item não pode ser anunciado no Mercado." }; if (seller.isItemLocked(itemId)) return { ok: false, reason: "Destrave este item antes de anunciá-lo." }; if (!Number.isInteger(quantity) || quantity < 1 || seller.inventory.quantity(itemId) < quantity) return { ok: false, reason: "Quantidade indisponível." }; if (seller.activeFruitId === itemId) return { ok: false, reason: "Desequipe a Akuma no Mi antes de anunciá-la." }; const valid = (value: number | undefined): value is number => value !== undefined && Number.isInteger(value) && value > 0; if (!valid(berriesPrice) && !valid(rubiesPrice) && !allowOffers) return { ok: false, reason: "Informe um preço ou aceite ofertas." }; seller.inventory.remove(itemId, quantity); const listing: Listing = { id: randomUUID(), sellerId: seller.id, itemId, quantity, berriesPrice: valid(berriesPrice) ? berriesPrice : null, rubiesPrice: valid(rubiesPrice) ? rubiesPrice : null, allowOffers, status: "ACTIVE", createdAt: now, expiresAt: now + TWO_DAYS }; this.listings.set(listing.id, listing); return { ok: true }; }
  buy(buyer: PlayerDomain, listingId: string, currency: Currency, now = Date.now()): Result { this.expire(now); const listing = this.listings.get(listingId); if (!listing || listing.status !== "ACTIVE") return { ok: false, reason: "Anúncio indisponível." }; if (listing.sellerId === buyer.id) return { ok: false, reason: "Você não pode comprar seu próprio anúncio." }; if (!this.playerById(listing.sellerId)) return { ok: false, reason: "Vendedor indisponível." }; const price = currency === "BERRIES" ? listing.berriesPrice : listing.rubiesPrice; if (!price || !this.wallets.debit(buyer.wallet, currency, price, { playerId: buyer.id, source: "AUCTION_PURCHASE", referenceId: listing.id })) return { ok: false, reason: "Saldo insuficiente." }; this.settle(listing, buyer, currency, price, now); return { ok: true }; }
  offer(buyer: PlayerDomain, listingId: string, currency: Currency, amount: number, now = Date.now()): Result { this.expire(now); const listing = this.listings.get(listingId); if (!listing || listing.status !== "ACTIVE" || !listing.allowOffers) return { ok: false, reason: "Este anúncio não aceita ofertas." }; if (listing.sellerId === buyer.id) return { ok: false, reason: "Você não pode ofertar no próprio anúncio." }; if (!Number.isInteger(amount) || amount <= 0 || !this.wallets.reserve(buyer.wallet, currency, amount, { playerId: buyer.id, source: "AUCTION_RESERVE", referenceId: listingId })) return { ok: false, reason: "Saldo disponível insuficiente." }; const id = randomUUID(); this.offers.set(id, { id, listingId, buyerId: buyer.id, currency, amount, status: "ACTIVE", createdAt: now }); return { ok: true }; }
  accept(seller: PlayerDomain, listingId: string, offerId: string, now = Date.now()): Result { this.expire(now); const listing = this.listings.get(listingId), offer = this.offers.get(offerId); if (!listing || !offer || listing.sellerId !== seller.id || listing.status !== "ACTIVE" || offer.status !== "ACTIVE" || offer.listingId !== listingId) return { ok: false, reason: "Oferta indisponível." }; const buyer = this.playerById(offer.buyerId); if (!buyer || !this.wallets.settleReserved(buyer.wallet, offer.currency, offer.amount, { playerId: buyer.id, source: "AUCTION_PURCHASE", referenceId: listing.id })) return { ok: false, reason: "Comprador indisponível ou sem saldo reservado." }; offer.status = "ACCEPTED"; this.settle(listing, buyer, offer.currency, offer.amount, now); return { ok: true }; }
  reject(seller: PlayerDomain, listingId: string, offerId: string): Result { const listing = this.listings.get(listingId), offer = this.offers.get(offerId); if (!listing || !offer || listing.sellerId !== seller.id || offer.status !== "ACTIVE") return { ok: false, reason: "Oferta indisponível." }; this.refund(offer, "REJECTED"); return { ok: true }; }
  cancel(seller: PlayerDomain, listingId: string): Result { const listing = this.listings.get(listingId); if (!listing || listing.sellerId !== seller.id || listing.status !== "ACTIVE") return { ok: false, reason: "Anúncio indisponível." }; listing.status = "CANCELLED"; seller.inventory.add(listing.itemId, listing.quantity); this.refundListingOffers(listing.id); return { ok: true }; }
  expire(now = Date.now()): void { for (const listing of this.listings.values()) if (listing.status === "ACTIVE" && now >= listing.expiresAt) { listing.status = "EXPIRED"; this.playerById(listing.sellerId)?.inventory.add(listing.itemId, listing.quantity); this.refundListingOffers(listing.id); } }
  private settle(listing: Listing, buyer: PlayerDomain, currency: Currency, price: number, now: number): void { const seller = this.playerById(listing.sellerId); if (!seller) throw new Error("Seller disappeared during settlement"); const fee = auctionFee(price), net = price - fee; this.wallets.credit(seller.wallet, currency, net, { playerId: seller.id, source: "AUCTION_SALE", referenceId: listing.id }); if (fee) this.wallets.credit({ berries: 0, rubies: 0, reservedBerries: 0, reservedRubies: 0 }, currency, fee, { playerId: "system", source: "AUCTION_FEE", referenceId: listing.id }); buyer.inventory.add(listing.itemId, listing.quantity); buyer.gainFruit(listing.itemId); listing.status = "SOLD"; this.refundListingOffers(listing.id); void now; }
  private refundListingOffers(listingId: string): void { for (const offer of this.offers.values()) if (offer.listingId === listingId && offer.status === "ACTIVE") this.refund(offer, "CANCELLED"); }
  private refund(offer: Offer, status: Offer["status"]): void { const buyer = this.playerById(offer.buyerId); if (buyer) this.wallets.release(buyer.wallet, offer.currency, offer.amount, { playerId: buyer.id, source: "AUCTION_REFUND", referenceId: offer.listingId }); offer.status = status; }
}
