import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export type ContentCategory = "material" | "consumable" | "equipment" | "quest" | "misc";
export type ContentRarity = "COMMON" | "UNCOMMON" | "RARE" | "EPIC" | "LEGENDARY";
export type ItemEffectType = "RESTORE_HP" | "RESTORE_HP_PERCENT" | "RESTORE_MANA" | "RESTORE_MANA_PERCENT";
export interface ContentItem { id: string; displayName: string; description: string; category: ContentCategory; rarity: ContentRarity; iconPath: string; stackable: boolean; tradeable: boolean; marketable: boolean; sellable: boolean; shopBuyable: boolean; buyValue: number; sellValue: number; effects: { type: ItemEffectType; amount: number }[]; cooldownMs?: number; }
export interface ContentFruit { id: string; displayName: string; description: string; rarity: ContentRarity; iconPath: string; tradeable: boolean; marketable: boolean; droppable: boolean; sellableForBerries: boolean; sellableForRubies: boolean; acceptsOffers: boolean; stats: Partial<Record<"strength" | "defense" | "maxHp" | "maxMana" | "critChanceBps" | "evasionChanceBps", number>>; skillIds: [string, string, string, string]; skillStatuses: ["AVAILABLE" | "LOCKED" | "PLACEHOLDER", "AVAILABLE" | "LOCKED" | "PLACEHOLDER", "AVAILABLE" | "LOCKED" | "PLACEHOLDER", "AVAILABLE" | "LOCKED" | "PLACEHOLDER"]; }
export interface ContentData { contentVersion: number; updatedAt: string; items: ContentItem[]; fruits: ContentFruit[]; enemies: { id: string; displayName: string; huntId: string }[]; lootTables: Record<string, { itemId: string; chanceBps: number; minQuantity: number; maxQuantity: number }[]>; }
export class ContentValidationError extends Error {}
const effectTypes = new Set<ItemEffectType>(["RESTORE_HP", "RESTORE_HP_PERCENT", "RESTORE_MANA", "RESTORE_MANA_PERCENT"]);
const safeId = (id: string) => /^[a-z0-9_]+$/.test(id);
const item = (value: ContentItem): ContentItem => ({ ...value, marketable: value.marketable ?? value.tradeable, sellable: value.sellable ?? true, shopBuyable: value.shopBuyable ?? value.buyValue > 0, effects: value.effects ?? [] });
const fruit = (value: ContentFruit): ContentFruit => ({ ...value, marketable: value.marketable ?? value.tradeable, sellableForBerries: value.sellableForBerries ?? false, sellableForRubies: value.sellableForRubies ?? false, acceptsOffers: value.acceptsOffers ?? value.tradeable, skillStatuses: value.skillStatuses ?? ["AVAILABLE", "AVAILABLE", "AVAILABLE", "PLACEHOLDER"] });
const references = (data: ContentData, id: string) => Object.entries(data.lootTables).filter(([, entries]) => entries.some((entry) => entry.itemId === id)).map(([enemy]) => `${enemy} Loot Table`);

export class ContentRepository {
  constructor(private readonly path = resolve(dirname(fileURLToPath(import.meta.url)), "../../../data/content/content.json")) {}
  async read(): Promise<ContentData> { const raw = JSON.parse(await readFile(this.path, "utf8")) as ContentData; const data = { ...raw, items: raw.items.map(item), fruits: raw.fruits.map(fruit) }; validateContent(data); return data; }
  async save(data: ContentData): Promise<void> { validateContent(data); data.updatedAt = new Date().toISOString(); data.contentVersion += 1; await mkdir(dirname(this.path), { recursive: true }); const temp = `${this.path}.${process.pid}.tmp`; await writeFile(temp, `${JSON.stringify(data, null, 2)}\n`, "utf8"); await rename(temp, this.path); console.info("[ContentAdmin] Saved content", data.contentVersion); }
  async createItem(value: ContentItem): Promise<void> { const data = await this.read(); if (data.items.some((entry) => entry.id === value.id) || data.fruits.some((entry) => entry.id === value.id)) throw new ContentValidationError("ID já existe."); data.items.push(item(value)); await this.save(data); }
  async updateItem(id: string, value: ContentItem): Promise<void> { const data = await this.read(), index = data.items.findIndex((entry) => entry.id === id); if (index < 0) throw new ContentValidationError("Item não encontrado."); if (id !== value.id) throw new ContentValidationError("Alterar ID exige migração de referências."); data.items[index] = item(value); await this.save(data); }
  async deleteItem(id: string): Promise<void> { const data = await this.read(), users = references(data, id); if (users.length) throw new ContentValidationError(`Não é possível excluir. Referenciado por: ${users.join(", ")}.`); data.items = data.items.filter((entry) => entry.id !== id); await this.save(data); }
  async createFruit(value: ContentFruit): Promise<void> { const data = await this.read(); if (data.items.some((entry) => entry.id === value.id) || data.fruits.some((entry) => entry.id === value.id)) throw new ContentValidationError("ID já existe."); data.fruits.push(fruit(value)); await this.save(data); }
  async updateFruit(id: string, value: ContentFruit): Promise<void> { const data = await this.read(), index = data.fruits.findIndex((entry) => entry.id === id); if (index < 0) throw new ContentValidationError("Akuma no Mi não encontrada."); if (id !== value.id) throw new ContentValidationError("Alterar ID exige migração de referências."); data.fruits[index] = fruit(value); await this.save(data); }
  async deleteFruit(id: string): Promise<void> { const data = await this.read(), users = references(data, id); if (users.length) throw new ContentValidationError(`Não é possível excluir. Referenciado por: ${users.join(", ")}.`); data.fruits = data.fruits.filter((entry) => entry.id !== id); await this.save(data); }
  async updateLootTable(enemyId: string, entries: ContentData["lootTables"][string]): Promise<void> { const data = await this.read(); if (!data.enemies.some((enemy) => enemy.id === enemyId)) throw new ContentValidationError("Monstro não encontrado."); data.lootTables[enemyId] = entries; await this.save(data); }
  assetPath(kind: "items" | "fruits", id: string): { filePath: string; iconPath: string } { if (!safeId(id)) throw new ContentValidationError("ID inválido para asset."); const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../../assets"), folder = resolve(root, kind); return { filePath: resolve(folder, `${id}.png`), iconPath: `${kind}/${id}.png` }; }
}
export function validateContent(data: ContentData): void { if (!data || !Array.isArray(data.items) || !Array.isArray(data.fruits) || !Array.isArray(data.enemies) || !data.lootTables) throw new ContentValidationError("Estrutura de conteúdo inválida."); const ids = new Set<string>(); for (const entry of [...data.items, ...data.fruits]) { if (!safeId(entry.id) || !entry.displayName?.trim() || ids.has(entry.id)) throw new ContentValidationError(`ID inválido ou duplicado: ${entry.id}`); ids.add(entry.id); } for (const value of data.items) if (value.buyValue < 0 || value.sellValue < 0 || !Array.isArray(value.effects) || value.effects.some((effect) => !effectTypes.has(effect.type) || !Number.isFinite(effect.amount) || effect.amount < 0) || (value.category === "consumable" && (!value.effects.length || !value.cooldownMs || value.cooldownMs < 0))) throw new ContentValidationError(`Item inválido: ${value.id}`); for (const value of data.fruits) if (value.skillIds.length !== 4 || value.skillStatuses.length !== 4) throw new ContentValidationError(`Fruta precisa de quatro slots: ${value.id}`); const enemies = new Set(data.enemies.map((entry) => entry.id)); for (const [enemy, entries] of Object.entries(data.lootTables)) { if (!enemies.has(enemy)) throw new ContentValidationError(`Loot aponta para monstro inexistente: ${enemy}`); for (const entry of entries) if (!ids.has(entry.itemId) || !Number.isInteger(entry.chanceBps) || entry.chanceBps < 0 || entry.chanceBps > 10_000 || entry.minQuantity < 1 || entry.maxQuantity < entry.minQuantity) throw new ContentValidationError(`Drop inválido em ${enemy}.`); } }
