import { fruitDefinitions, hunts, itemDefinitions, type ClientIntent, type CombatFeedbackSnapshot, type Direction, type GameSnapshot, type ItemId } from "@onepiece/shared";
import { AutoHuntSkillPlanner } from "./auto-hunt.js";
import { ConsumableService } from "./consumables.js";
import { EnemyDomain, NpcDomain, PlayerDomain, alvidaConfig, buffaloConfig, cardinalDirection, directionVector, resolveCombat } from "./domain.js";
import { HuntAnalyzer } from "./hunt-analyzer.js";
import { canMoveTo, getEnemySpawnPoints, getMapDefinition, getPlayerSpawn } from "./map-definitions.js";
import { AuctionService } from "./auction.js";
import { WalletService } from "./economy.js";
import { publicCatalog } from "./public-catalog.js";

const standaloneWallets = new WalletService();
const standaloneAuction = new AuctionService(standaloneWallets, () => undefined);

/** One isolated Alpha world instance per connection. It can later load/save a persistent player. */
export class GameSession {
  readonly player: PlayerDomain; readonly analyzer = new HuntAnalyzer(); readonly npc: NpcDomain; readonly feedback: CombatFeedbackSnapshot[] = [];
  readonly planner = new AutoHuntSkillPlanner(false); readonly consumables = new ConsumableService(); area: GameSnapshot["area"] = "pirate_ship"; enemies: EnemyDomain[]; private nextEnemyId = 4; private feedbackSequence = 0; private readonly logs: string[] = []; private deathHandled = false; private respawnAt: number | null = null; private readonly enemyLifecycle = new Map<string, { type: EnemyDomain["snapshot"]["type"]; removeAt: number; respawnAt: number }>();
  constructor(readonly id: string, private readonly wallets: WalletService = standaloneWallets, private readonly auction: AuctionService = standaloneAuction) { this.player = new PlayerDomain(id); const spawn = getPlayerSpawn(this.area); this.player.x = spawn.x; this.player.y = spawn.y; const npcSpawn = getMapDefinition("pirate_ship").npcSpawns[0]; if (!npcSpawn) throw new Error("[MapData] pirate_ship requires old_drunk NPC spawn."); this.npc = new NpcDomain(npcSpawn); this.enemies = []; this.log("Ted iniciou a jornada no Barco Pirata."); }
  private log(message: string): void { this.logs.push(message); }
  drainLogs(): string[] { return this.logs.splice(0); }
  private createEnemies(type: EnemyDomain["snapshot"]["type"]): EnemyDomain[] { const prefix = type === "enemy_buffalo" ? "buffalo" : "alvida"; return getEnemySpawnPoints(this.area).slice(0, 3).map(({ x, y }, index) => new EnemyDomain(`${prefix}_${this.nextEnemyId++}_${index}`, x, y, type)); }
  private randomSpawn(type: EnemyDomain["snapshot"]["type"]): readonly [number, number] { const points = getEnemySpawnPoints(this.area); const free = points.filter(({ x, y }) => !this.enemies.some((enemy) => enemy.snapshot.state !== "DEAD" && Math.hypot(enemy.snapshot.x - x, enemy.snapshot.y - y) < 130)); const selected = free[Math.floor(Math.random() * free.length)] ?? points[Math.floor(Math.random() * points.length)]; return [selected.x, selected.y]; }
  private scheduleEnemyRespawn(enemy: EnemyDomain, now: number): void { if (this.enemyLifecycle.has(enemy.snapshot.id)) return; this.enemyLifecycle.set(enemy.snapshot.id, { type: enemy.snapshot.type, removeAt: now + 500, respawnAt: now + 3000 }); this.log(`[EnemyLifecycle] ${enemy.snapshot.id} ${enemy.snapshot.type} ALIVE→DEAD; RESPAWN_SCHEDULED`); }
  private processEnemyLifecycle(now: number): void { for (const [id, lifecycle] of this.enemyLifecycle) { if (now >= lifecycle.removeAt && this.enemies.some((enemy) => enemy.snapshot.id === id)) { this.enemies = this.enemies.filter((enemy) => enemy.snapshot.id !== id); this.log(`[EnemyLifecycle] ${id} REMOVED`); } if (now >= lifecycle.respawnAt) { const [x, y] = this.randomSpawn(lifecycle.type); const prefix = lifecycle.type === "enemy_buffalo" ? "buffalo" : "alvida"; const enemy = new EnemyDomain(`${prefix}_${this.nextEnemyId++}`, x, y, lifecycle.type); this.enemies.push(enemy); this.enemyLifecycle.delete(id); this.log(`[EnemyLifecycle] ${enemy.snapshot.id} ${lifecycle.type} RESPAWNED`); } } }
  private pushFeedback(entry: Omit<CombatFeedbackSnapshot, "id" | "createdAt">): void { this.feedback.push({ ...entry, id: `feedback_${++this.feedbackSequence}`, createdAt: Date.now() }); }
  private useItem(itemId: ItemId, now: number, auto = false): boolean { const result = this.consumables.use(this.player, itemId, now); if (!result.ok) return false; const text = `+${result.restoredHp} HP`; this.pushFeedback({ target: "player", x: this.player.x, y: this.player.y - 145, text, kind: "status" }); this.log(`${auto ? "Auto: " : ""}${itemDefinitions[itemId].displayName} utilizada: ${text}.`); return true; }
  private autoPotion(now: number): void { const s = this.player.autoHuntSettings; if (this.player.isDead || this.player.autoHunt === "OFF" || !s.autoUseConsumables || !s.hpPotionEnabled || this.player.resources.currentHp / this.player.stats.maxHp * 100 > s.hpThresholdPercent) return; const slots = s.utilityMode === "SLOT_1" ? [this.player.utilitySlots[0]] : s.utilityMode === "SLOT_2" ? [this.player.utilitySlots[1]] : [...this.player.utilitySlots]; const ids = slots.filter((id): id is ItemId => Boolean(id)); for (const id of ids) if (this.useItem(id, now, true)) break; }
  snapshot(now = Date.now()): GameSnapshot { this.autoPotion(now); while (this.feedback.length && now - this.feedback[0].createdAt > 1400) this.feedback.shift(); return { area: this.area, player: this.player.snapshot(), enemies: this.enemies.map((enemy) => enemy.snapshot), npcs: this.area === "pirate_ship" ? [this.npc.snapshot] : [], huntAnalyzer: this.analyzer.snapshot(now), combatFeedback: [...this.feedback], auction: this.auction.snapshotFor(this.player.id, now), contentCatalog: { items: Object.values(itemDefinitions), fruits: Object.values(fruitDefinitions), public: publicCatalog(), discovery: { items: [...this.player.discoveredItems], fruits: [...this.player.discoveredFruits], enemies: [...this.player.discoveredEnemies], hunts: [...this.player.discoveredHunts] } } }; }
  private targetInRange(): EnemyDomain | undefined { return this.enemies.filter((enemy) => enemy.snapshot.state !== "DEAD" && Math.hypot(enemy.snapshot.x - this.player.x, enemy.snapshot.y - this.player.y) <= this.player.stats.attackRange).sort((a, b) => Math.hypot(a.snapshot.x - this.player.x, a.snapshot.y - this.player.y) - Math.hypot(b.snapshot.x - this.player.x, b.snapshot.y - this.player.y))[0]; }
  private autoTarget(): EnemyDomain | undefined { const candidates = this.enemies.filter((enemy) => enemy.snapshot.state !== "DEAD"); const [dx, dy] = directionVector(this.player.direction); const ahead = candidates.filter((enemy) => (enemy.snapshot.x - this.player.x) * dx + (enemy.snapshot.y - this.player.y) * dy > 0); return (ahead.length ? ahead : candidates).sort((a, b) => Math.hypot(a.snapshot.x - this.player.x, a.snapshot.y - this.player.y) - Math.hypot(b.snapshot.x - this.player.x, b.snapshot.y - this.player.y))[0]; }
  private dealHit(target: EnemyDomain, attack: number, now: number, label?: string, fixed = false): void { this.player.direction = cardinalDirection(target.snapshot.x - this.player.x, target.snapshot.y - this.player.y); const before = target.snapshot.hp; const result = fixed ? { damage: attack, critical: false, dodged: false } : resolveCombat(attack, target.definition.defense, this.player.stats.critChanceBps); if (!result.dodged) target.damage(result.damage); const damage = before - target.snapshot.hp; if (damage) this.pushFeedback({ target: "enemy", targetId: target.snapshot.id, x: target.snapshot.x, y: target.snapshot.y - 110, text: label ? `${label} ${damage}` : `${result.critical ? "CRÍTICO " : "-"}${damage}`, kind: result.critical ? "critical" : "damage" }); this.analyzer.recordDamageDealt(damage, result.critical); if (!target.claimReward()) return;
    const drops = target.loot(); for (const drop of drops) { if (drop.itemId.startsWith("fruit_")) this.player.gainFruit(drop.itemId); const beforeQuantity = this.player.inventory.quantity(drop.itemId as ItemId); this.player.inventory.add(drop.itemId as ItemId, drop.quantity); if (process.env.NODE_ENV !== "production") console.info(`[ContentLoot] enemy=${target.snapshot.type} item=${drop.itemId} chance=resolved result=DROP quantity=${drop.quantity} inventory=${beforeQuantity}->${this.player.inventory.quantity(drop.itemId as ItemId)}`); for (let i = 0; i < drop.quantity; i++) this.analyzer.recordLoot(drop.itemId as ItemId); }
    const progress = this.player.gainXp(target.definition.xpReward); this.wallets.credit(this.player.wallet, "BERRIES", target.definition.berriesReward, { playerId: this.player.id, source: "ENEMY_REWARD", referenceId: target.snapshot.id }); this.analyzer.recordKill(target.snapshot.type); this.analyzer.recordXp(target.definition.xpReward); this.analyzer.recordBerries(target.definition.berriesReward); this.scheduleEnemyRespawn(target, now); this.log(`${target.snapshot.type === "enemy_buffalo" ? "Buffalo" : "Alvida"} derrotada. +${target.definition.xpReward} XP, +${target.definition.berriesReward} Berries${drops.length ? `: ${drops.map((drop) => drop.itemId).join(", ")} coletados` : ""}.`); if (progress.levelsGained) this.log(`LEVEL UP! Lv. ${progress.oldLevel} → Lv. ${progress.newLevel}.`);
  }
  private attack(now: number): boolean { const target = this.targetInRange(); if (!target || !this.player.canAttack(now)) return false; this.player.attacked(now); this.dealHit(target, this.player.attackPower, now); return true; }
  private castSkill(skillId: string, now: number): boolean { const target = this.targetInRange(); if (skillId === "sube_bubbles") { if (!target || !this.player.useSkill(skillId, now)) return false; this.player.attacked(now); const damage = 10 + Math.ceil(target.definition.attackPower * .03); for (let hit = 1; hit <= 3 && target.snapshot.state !== "DEAD"; hit++) this.dealHit(target, damage, now, `BOLHAS ${hit}/3 -`, true); return true; }
    if (skillId === "guro_blast") { if (!target || !this.player.useSkill(skillId, now)) return false; this.dealHit(target, 24 + this.player.attackPower, now, "EXPLOSÃO -", true); return true; }
    if (skillId === "guro_spin") return Boolean(target && this.player.useSkill(skillId, now));
    if (skillId === "guro_crush") { if (!target || !this.player.useSkill(skillId, now)) return false; this.dealHit(target, 40 + this.player.attackPower * 2, now, "IMPACTO -", true); return true; }
    return this.player.useSkill(skillId, now);
  }
  handle(intent: ClientIntent, now = Date.now()): void { if (this.player.isDead) { if (intent.type === "requestRespawn") this.respawnToShip(); return; } if (intent.type === "move") { const x = Math.sign(intent.x), y = Math.sign(intent.y); if (!x && !y) this.player.stop(); else if (!(x && y)) this.player.move(x < 0 ? "left" : x > 0 ? "right" : y < 0 ? "up" : "down", 20, (nextX, nextY) => !canMoveTo(this.area, nextX, nextY)); }
    else if (intent.type === "attack") this.attack(now);
    else if (intent.type === "useItem") { if (!this.useItem(intent.itemId, now)) this.log(this.player.resources.currentHp >= this.player.stats.maxHp ? "Vida já está cheia." : "Item não pode ser usado agora."); }
    else if (intent.type === "setUtilitySlot") { const definition = itemDefinitions[intent.itemId]; if (!definition?.usable || !definition.consumable || !this.player.inventory.quantity(intent.itemId) || this.player.utilitySlots[1 - intent.slot] === intent.itemId) this.log("Utilidade inválida ou duplicada."); else this.player.utilitySlots[intent.slot] = intent.itemId; }
    else if (intent.type === "clearUtilitySlot") this.player.utilitySlots[intent.slot] = null;
    else if (intent.type === "updateAutoHuntSettings") { const s = { ...this.player.autoHuntSettings, ...intent.settings }; if (Number.isInteger(s.hpThresholdPercent) && Number.isInteger(s.manaThresholdPercent) && s.hpThresholdPercent >= 1 && s.hpThresholdPercent <= 99 && s.manaThresholdPercent >= 1 && s.manaThresholdPercent <= 99 && ["SMALL_FIRST", "LARGE_FIRST", "SMART"].includes(s.potionPreference)) this.player.autoHuntSettings = s; else this.log("Configuração do Bot inválida."); }
    else if (intent.type === "useSkill" && !this.castSkill(intent.skillId, now)) this.log("Habilidade indisponível: equipe a fruta correta, aguarde o cooldown e fique no alcance.");
    else if (intent.type === "toggleAutoHunt") { this.player.autoHunt = this.player.autoHunt === "OFF" ? "SEARCHING" : "OFF"; this.log(`Auto-Hunt: ${this.player.autoHunt}`); }
    else if (intent.type === "equipFruit") { try { this.player.equipFruit(intent.fruitId); this.log(`${intent.fruitId} equipada.`); } catch { this.log("Akuma no Mi não obtida."); } }
    else if (intent.type === "unequipFruit") { this.player.unequipFruit(); this.log("Akuma no Mi desequipada."); }
    else if (intent.type === "enterHunt") { const hunt = hunts.find((entry) => entry.id === intent.huntId); if (!hunt) { this.log("Hunt indisponível."); return; } const buffalo = hunt.mainEnemyId === "enemy_buffalo"; this.area = hunt.mapId; this.enemyLifecycle.clear(); this.analyzer.start(hunt.id, now); this.player.discoverHunt(hunt.id); const spawn = getPlayerSpawn(this.area); this.player.x = spawn.x; this.player.y = spawn.y; this.player.state = "IDLE"; this.player.autoHunt = "OFF"; this.enemies = this.createEnemies(buffalo ? "enemy_buffalo" : "enemy_alvida"); this.log(`Ted viajou para ${hunt.displayName}. Auto-Hunt desligado.`); }
    else if (intent.type === "leaveHunt") this.returnToShip(now);
    else if (intent.type === "buyItem") { const definition = itemDefinitions[intent.itemId], price = definition?.buyValue; if (!definition?.shopBuyable || !price) this.log("Item não está à venda."); else if (!this.wallets.debit(this.player.wallet, "BERRIES", price, { playerId: this.player.id, source: "SHOP_PURCHASE", referenceId: intent.itemId })) this.log("Berries insuficientes."); else { this.player.inventory.add(intent.itemId, 1); this.log(`${definition.displayName} comprada.`); } }
    else if (intent.type === "depositItem") { const error = this.player.transferToStorage(intent.itemId, intent.quantity); this.log(error ?? `${itemDefinitions[intent.itemId]?.displayName ?? "Item"} x${intent.quantity} enviado ao Depósito.`); }
    else if (intent.type === "withdrawItem") { const error = this.player.transferFromStorage(intent.itemId, intent.quantity); this.log(error ?? `${itemDefinitions[intent.itemId]?.displayName ?? "Item"} x${intent.quantity} retirado do Depósito.`); }
    else if (intent.type === "sellItems") { let berries = 0; for (const id of intent.itemIds) { const definition = itemDefinitions[id]; if (!definition?.sellable || definition.category === "fruit") continue; berries += this.player.inventory.remove(id) * definition.sellValue; } if (berries) { this.wallets.credit(this.player.wallet, "BERRIES", berries, { playerId: this.player.id, source: "ITEM_SELL" }); this.log(`Itens vendidos por ${berries} Berries.`); } }
    else if (intent.type === "createAuctionListing") { const result = this.auction.createListing(this.player, intent.itemId, intent.quantity, intent.berriesPrice, intent.rubiesPrice, intent.allowOffers, now); this.log(result.ok ? "Anúncio criado e item colocado em escrow." : result.reason); }
    else if (intent.type === "buyAuctionListing") { const result = this.auction.buy(this.player, intent.listingId, intent.currency, now); this.log(result.ok ? "Compra concluída. Taxa de 10% aplicada ao vendedor." : result.reason); }
    else if (intent.type === "cancelAuctionListing") { const result = this.auction.cancel(this.player, intent.listingId); this.log(result.ok ? "Anúncio cancelado e item devolvido." : result.reason); }
    else if (intent.type === "createAuctionOffer") { const result = this.auction.offer(this.player, intent.listingId, intent.currency, intent.amount, now); this.log(result.ok ? "Oferta enviada; saldo reservado em escrow." : result.reason); }
    else if (intent.type === "acceptAuctionOffer") { const result = this.auction.accept(this.player, intent.listingId, intent.offerId, now); this.log(result.ok ? "Oferta aceita e transação concluída." : result.reason); }
    else if (intent.type === "rejectAuctionOffer") { const result = this.auction.reject(this.player, intent.listingId, intent.offerId); this.log(result.ok ? "Oferta recusada e saldo devolvido." : result.reason); }
    else if (intent.type === "interactWithNpc") { const result = this.npc.interact(intent.npcId, this.player, now); this.log(result === "HEALED" ? "Velho Bêbado restaurou sua vida." : result === "FULL_HEALTH" ? "Você já está com a vida cheia." : result === "TOO_FAR" ? "Chegue mais perto." : result === "COOLDOWN" ? "O Velho Bêbado ainda está servindo o gole." : result === "PLAYER_DEAD" ? "Você precisa estar vivo para conversar." : "Esse NPC não existe."); }
    else if (intent.type === "resetHuntAnalyzer" && this.analyzer.snapshot(now).huntId) this.analyzer.reset(this.analyzer.snapshot(now).huntId!, now);
    else if (intent.type === "requestRespawn") this.respawnToShip();
  }
  private handlePlayerDeath(now: number): void { if (this.deathHandled) return; this.deathHandled = true; this.player.resources.currentHp = 0; this.player.state = "DEAD"; this.player.cancelPendingActions(); this.analyzer.recordDeath(); this.respawnAt = now + 1800; this.log(`[DeathDebug] ${this.id} ALIVE→DEAD hp=0 area=${this.area} auto=OFF`); this.log("Ted foi derrotado. Retornando ao barco..."); }
  private returnToShip(now: number): void { if (this.area === "pirate_ship") return; this.analyzer.end(now); this.enemyLifecycle.clear(); this.enemies = []; this.area = "pirate_ship"; const spawn = getPlayerSpawn(this.area); this.player.x = spawn.x; this.player.y = spawn.y; this.player.state = "IDLE"; this.player.autoHunt = "OFF"; this.log("Ted retornou ao Barco Pirata."); }
  private respawnToShip(): void { if (!this.player.isDead || !this.deathHandled) return; this.log(`[DeathDebug] ${this.id} DEAD→RESPAWNING area=${this.area}`); this.analyzer.end(); this.area = "pirate_ship"; this.player.healFull(); const spawn = getPlayerSpawn(this.area); this.player.x = spawn.x; this.player.y = spawn.y; this.player.state = "IDLE"; this.player.autoHunt = "OFF"; this.respawnAt = null; this.deathHandled = false; this.log(`[DeathDebug] ${this.id} RESPAWNING→ALIVE area=pirate_ship`); this.log("Ted retornou ao barco para se recuperar."); }
  tick(now = Date.now()): void { this.player.tick(now); this.npc.tick(now); this.processEnemyLifecycle(now); if (this.player.isDead) { if (this.respawnAt !== null && now >= this.respawnAt) this.respawnToShip(); return; } if (this.area === "pirate_ship") return; const config = this.area === "beach_buffalo" ? buffaloConfig : alvidaConfig; for (const enemy of this.enemies) if (enemy.tick(this.player, now, config.moveSpeed * .3, (x, y) => !canMoveTo(this.area, x, y))) { const hit = resolveCombat(enemy.definition.attackPower, this.player.defenseAt(now), 0, this.player.evasionAt(now)); this.player.receiveDamage(hit.damage); if (hit.dodged) { this.analyzer.recordDodge(); this.pushFeedback({ target: "player", x: this.player.x, y: this.player.y - 125, text: "ESQUIVOU", kind: "dodge" }); } else { this.analyzer.recordDamageTaken(hit.damage); this.pushFeedback({ target: "player", x: this.player.x, y: this.player.y - 125, text: `-${hit.damage}`, kind: "damage" }); } if (this.player.isDead) { this.handlePlayerDeath(now); break; } }
    const target = this.targetInRange(); if (target && this.player.consumeGuroSpinTick(now)) { this.dealHit(target, 14, now, "RODOPIO -", true); this.pushFeedback({ target: "player", x: this.player.x, y: this.player.y - 175, text: "RODOPIO", kind: "status" }); }
    if (this.player.autoHunt !== "OFF") { const autoTarget = this.autoTarget(); if (!autoTarget) return; const dx = autoTarget.snapshot.x - this.player.x, dy = autoTarget.snapshot.y - this.player.y; if (Math.hypot(dx, dy) <= this.player.stats.attackRange) { this.player.autoHunt = "ATTACKING"; this.attack(now); } else { this.player.autoHunt = "MOVING_TO_TARGET"; this.player.move(cardinalDirection(dx, dy), 20, (x, y) => !canMoveTo(this.area, x, y)); } }
  }
}
