import { Eye, EyeOff, Volume2, VolumeX } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";
import "./auth-gateway.css";
const logoUrl = "/intro/project-one-logo.png";
const backgroundUrl = "/intro/project-one-background.png";
type Phase = "LANDING" | "LOGIN" | "REGISTER" | "AUTHENTICATING" | "LOADING_GAME";
type AuthResult = { ok: boolean; message?: string; session?: { token: string; username: string } };
const api = async (path: string, data: Record<string, string>): Promise<AuthResult> => { try { const response = await fetch(`http://localhost:8787/api/auth/${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); return await response.json() as AuthResult; } catch { return { ok: false, message: "Servidor indisponível." }; } };
export function AuthGateway({ onAuthenticated }: { onAuthenticated: (token: string) => void }): JSX.Element {
  const [phase, setPhase] = useState<Phase>("LANDING"), [muted, setMuted] = useState(() => localStorage.getItem("project-one-muted") === "true"), [message, setMessage] = useState(""), [showPassword, setShowPassword] = useState(false);
  const audio = useRef<HTMLAudioElement>(); if (!audio.current) { audio.current = new Audio("/songs/0923.opus"); audio.current.loop = true; audio.current.volume = .28; }
  useEffect(() => { audio.current!.muted = muted; localStorage.setItem("project-one-muted", String(muted)); }, [muted]);
  useEffect(() => () => { audio.current?.pause(); }, []);
  const begin = () => { void audio.current?.play().catch(() => undefined); setPhase("LOGIN"); };
  const authenticate = async (event: FormEvent<HTMLFormElement>, kind: "login" | "register") => { event.preventDefault(); const form = new FormData(event.currentTarget); const password = String(form.get("password") ?? ""); if (kind === "register" && password !== form.get("confirm")) return setMessage("As senhas não coincidem."); setMessage(""); setPhase("AUTHENTICATING"); const result = await api(kind, kind === "login" ? { identity: String(form.get("identity") ?? ""), password } : { username: String(form.get("username") ?? ""), email: String(form.get("email") ?? ""), password }); if (!result.ok || !result.session) { setMessage(result.message ?? "Não foi possível autenticar."); return setPhase(kind === "login" ? "LOGIN" : "REGISTER"); } localStorage.setItem("project-one-session", result.session.token); setPhase("LOADING_GAME"); window.setTimeout(() => { onAuthenticated(result.session!.token); const track = audio.current!; const fade = window.setInterval(() => { track.volume = Math.max(0, track.volume - .03); if (track.volume === 0) { track.pause(); window.clearInterval(fade); } }, 160); }, 650); };
  const form = phase === "REGISTER" ? <form onSubmit={(event) => void authenticate(event, "register")}><h2>Cadastre-se</h2><label>Nome de usuário<input name="username" required minLength={3} maxLength={20} autoComplete="username" /></label><label>E-mail<input name="email" type="email" required autoComplete="email" /></label><Password show={showPassword} setShow={setShowPassword} /><label>Confirmar senha<input name="confirm" type={showPassword ? "text" : "password"} required autoComplete="new-password" /></label><button className="auth-primary">CRIAR CONTA</button><button type="button" className="auth-link" onClick={() => { setMessage(""); setPhase("LOGIN"); }}>VOLTAR AO LOGIN</button></form> : <form onSubmit={(event) => void authenticate(event, "login")}><h2>Entrar</h2><label>Usuário ou e-mail<input name="identity" required autoComplete="username" autoFocus /></label><Password show={showPassword} setShow={setShowPassword} /><button className="auth-primary" disabled={phase === "AUTHENTICATING"}>{phase === "AUTHENTICATING" ? "ENTRANDO..." : "ENTRAR"}</button><button type="button" className="auth-link" onClick={() => { setMessage(""); setPhase("REGISTER"); }}>CRIAR CONTA</button></form>;
  return <main className={`auth-gateway ${phase !== "LANDING" ? "started" : ""}`} style={{ backgroundImage: `url(${backgroundUrl})` }}><div className="auth-vignette" /><button className="auth-mute" aria-label={muted ? "Ativar música" : "Silenciar música"} onClick={() => setMuted((value) => !value)}>{muted ? <VolumeX /> : <Volume2 />}</button><img className="auth-logo" src={logoUrl} alt="Project One" />{phase === "LANDING" ? <button className="auth-start" onClick={begin}><span>✦</span> CLIQUE PARA INICIAR <small>CLOSED ALPHA · 0.1.0</small></button> : phase === "LOADING_GAME" ? <section className="auth-loading"><img src={logoUrl} alt="" /><b>Carregando aventura...</b></section> : <section className="auth-card"><img src={logoUrl} alt="Project One" />{form}{message && <p role="alert" className="auth-message">{message}</p>}</section>}<footer>PROJECT ONE · CLOSED ALPHA</footer></main>;
}
function Password({ show, setShow }: { show: boolean; setShow: (value: boolean) => void }): JSX.Element { return <label>Senha<span className="password-input"><input name="password" type={show ? "text" : "password"} required minLength={8} autoComplete="current-password" /><button type="button" aria-label={show ? "Ocultar senha" : "Mostrar senha"} onClick={() => setShow(!show)}>{show ? <EyeOff size={16} /> : <Eye size={16} />}</button></span></label>; }
