import { useMemo, useState } from "react";
import { skillDefinitions, type GameSnapshot, type PublicCatalogDrop } from "@onepiece/shared";

type Tab = "fruits" | "items" | "consumables" | "enemies" | "hunts";
type Entry = { id: string; displayName: string; description?: string; rarity?: string; iconPath?: string; [key: string]: any };
const tabs: { id: Tab; label: string }[] = [{ id: "fruits", label: "Akuma no Mi" }, { id: "items", label: "Itens" }, { id: "consumables", label: "Consumíveis" }, { id: "enemies", label: "Monstros" }, { id: "hunts", label: "Hunts" }];
const pct = (bps: number) => `${(bps / 100).toLocaleString("pt-BR", { maximumFractionDigits: 2 })}%`;
const effect = (raw: unknown) => { const e = raw as { type: string; amount: number }; const label: Record<string, string> = { RESTORE_HP: "Recupera", RESTORE_HP_PERCENT: "Recupera", RESTORE_MANA: "Restaura", RESTORE_MANA_PERCENT: "Restaura" }; const unit = e.type.includes("PERCENT") ? "% da Vida máxima" : e.type.includes("MANA") ? " de Mana" : " de Vida"; return `${label[e.type] ?? e.type} ${e.amount}${unit}`; };
const image = (path?: string) => path ? `/${path}` : "/personagem/Player/idle/1.png";

export function CatalogPanel({ snapshot }: { snapshot?: GameSnapshot }): JSX.Element {
  const [tab, setTab] = useState<Tab>("fruits"); const [query, setQuery] = useState(""); const [rarity, setRarity] = useState("ALL"); const [sort, setSort] = useState("name"); const [selected, setSelected] = useState<Entry | null>(null);
  const catalog = snapshot?.contentCatalog.public;
  const discovery = snapshot?.contentCatalog.discovery;
  const all = useMemo<Entry[]>(() => tab === "fruits" ? (catalog?.fruits ?? []) : tab === "items" ? (catalog?.items ?? []).filter((item) => item.category !== "consumable") : tab === "consumables" ? (catalog?.items ?? []).filter((item) => item.category === "consumable") : tab === "enemies" ? (catalog?.enemies ?? []) : (catalog?.hunts ?? []), [catalog, tab]);
  const discovered = (entry: Entry) => tab === "fruits" ? Boolean(discovery?.fruits.includes(entry.id) || snapshot?.player.ownedFruitIds.includes(entry.id)) : tab === "items" || tab === "consumables" ? Boolean(discovery?.items.includes(entry.id) || snapshot?.player.inventory.some((stack) => stack.itemId === entry.id)) : tab === "enemies" ? Boolean(discovery?.enemies.includes(entry.id) || snapshot?.enemies.some((enemy) => enemy.type === entry.id)) : Boolean(discovery?.hunts.includes(entry.id) || snapshot?.huntAnalyzer.huntId === entry.id);
  const entries = all.filter((entry) => (rarity === "ALL" || entry.rarity === rarity) && `${entry.displayName} ${entry.id} ${entry.description ?? ""}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === "rarity" ? String(a.rarity ?? "").localeCompare(String(b.rarity ?? "")) : sort === "unknown" ? Number(discovered(a)) - Number(discovered(b)) : sort === "known" ? Number(discovered(b)) - Number(discovered(a)) : a.displayName.localeCompare(b.displayName));
  const known = all.filter(discovered).length; const rarities = [...new Set(all.map((entry) => entry.rarity).filter(Boolean))] as string[];
  if (!catalog) return <p className="empty-note">Carregando conteúdo público…</p>;
  return <section className="catalog-panel"><header className="catalog-header"><div><span className="eyebrow">COMPÊNDIO DO MAR</span><b>{known} / {all.length} DESCOBERTOS</b><i><em style={{ width: `${all.length ? known / all.length * 100 : 0}%` }} /></i></div><small>Descobertas ficam apenas nesta sessão por enquanto.</small></header><nav className="catalog-tabs">{tabs.map((entry) => <button key={entry.id} className={tab === entry.id ? "active" : ""} onClick={() => { setTab(entry.id); setSelected(null); }}>{entry.label}</button>)}</nav><div className="catalog-body"><aside><label>BUSCAR<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nome, ID ou descrição" /></label><label>RARIDADE<select value={rarity} onChange={(event) => setRarity(event.target.value)}><option value="ALL">Todas</option>{rarities.map((value) => <option key={value}>{value}</option>)}</select></label><label>ORDENAR<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="name">Nome A–Z</option><option value="rarity">Raridade</option><option value="known">Descoberto primeiro</option><option value="unknown">Não descoberto primeiro</option></select></label></aside><main className="catalog-grid">{entries.map((entry) => { const isKnown = discovered(entry); return <button key={entry.id} className={`catalog-card ${isKnown ? "" : "unknown"}`} onClick={() => setSelected(entry)}><img src={image(entry.iconPath)} onError={(event) => { event.currentTarget.style.opacity = "0.2"; }} alt="" /><b>{isKnown ? entry.displayName : "?????"}</b><span>{isKnown ? (entry.rarity ?? "—") : "Não descoberta"}</span><small>{isKnown ? entry.description ?? "Informações públicas disponíveis." : "Encontre este conteúdo para revelar."}</small></button>; })}{!entries.length && <p className="empty-note">Nenhum conteúdo encontrado.</p>}</main>{selected && <CatalogDetail entry={selected} known={discovered(selected)} catalog={catalog} onBack={() => setSelected(null)} />}</div></section>;
}

function Drops({ drops }: { drops: PublicCatalogDrop[] | { enemyName: string; chanceBps: number; minQuantity: number; maxQuantity: number }[] }): JSX.Element { return <ul className="catalog-drops">{drops.length ? drops.map((drop, index) => { const name = "enemyName" in drop ? drop.enemyName : drop.itemId; return <li key={`${name}-${index}`}><b>{name}</b><span>{pct(drop.chanceBps)} · ×{drop.minQuantity}{drop.maxQuantity !== drop.minQuantity ? `–${drop.maxQuantity}` : ""}</span></li>; }) : <li>—</li>}</ul>; }
function CatalogDetail({ entry, known, catalog, onBack }: { entry: Entry; known: boolean; catalog: NonNullable<GameSnapshot["contentCatalog"]["public"]>; onBack: () => void }): JSX.Element { if (!known) return <aside className="catalog-detail unknown"><button onClick={onBack}>← VOLTAR</button><h3>Não descoberta</h3><p>Continue explorando para registrar este conteúdo no compêndio.</p></aside>; const item = entry as Entry & { effects?: unknown[]; drops?: PublicCatalogDrop[]; stats?: Record<string, number>; skillIds?: string[]; skillStatuses?: string[]; maxHp?: number; xpReward?: number; berriesReward?: number; mainEnemyId?: string; recommendedLevelMin?: number; recommendedLevelMax?: number; difficulty?: number; stackable?: boolean; tradeable?: boolean; marketable?: boolean; sellValue?: number; buyValue?: number; cooldownMs?: number };
  const monster = item.mainEnemyId ? catalog.enemies.find((enemy) => enemy.id === item.mainEnemyId) : undefined;
  return <aside className="catalog-detail"><button onClick={onBack}>← VOLTAR</button><img src={image(item.iconPath)} alt="" /><span className="eyebrow">{item.rarity ?? "REGISTRO"}</span><h3>{item.displayName}</h3><p>{item.description ?? "Informações públicas disponíveis."}</p>{item.skillIds && <><h4>HABILIDADES</h4><div className="catalog-skills">{Array.from({ length: 4 }, (_, index) => { const skill = skillDefinitions[item.skillIds![index]]; const locked = item.skillStatuses?.[index] !== "AVAILABLE" || !skill || skill.status !== "AVAILABLE"; return <article key={index} className={locked ? "locked" : ""}><b>{locked ? "BLOQUEADA" : skill.displayName}</b><small>{locked ? "—" : `${skill.manaCost} mana · ${skill.cooldownMs / 1000}s`}</small><p>{locked ? "Slot indisponível" : skill.description}</p></article>; })}</div></>}{item.stats && Object.keys(item.stats).length > 0 && <><h4>ATRIBUTOS</h4><div className="catalog-stats">{Object.entries(item.stats).map(([name, value]) => <span key={name}>{name} <b>+{name.includes("Bps") ? `${value / 100}%` : value}</b></span>)}</div></>}{item.maxHp !== undefined && <div className="catalog-stats"><span>HP <b>{item.maxHp}</b></span><span>XP <b>{item.xpReward}</b></span><span>Berries <b>{item.berriesReward}</b></span></div>}{item.recommendedLevelMin !== undefined && <div className="catalog-stats"><span>Nível <b>{item.recommendedLevelMin}–{item.recommendedLevelMax}</b></span><span>Dificuldade <b>{item.difficulty}</b></span><span>Inimigo <b>{monster?.displayName ?? "—"}</b></span></div>}{item.effects?.length ? <><h4>EFEITOS</h4><p>{item.effects.map(effect).join(" · ")}{item.cooldownMs ? ` · Cooldown ${item.cooldownMs / 1000}s` : ""}</p></> : null}{item.stackable !== undefined && <div className="catalog-stats"><span>Empilhável <b>{item.stackable ? "Sim" : "Não"}</b></span><span>Negociável <b>{item.tradeable ? "Sim" : "Não"}</b></span><span>Venda <b>{item.sellValue ?? 0} B</b></span>{item.buyValue ? <span>Compra <b>{item.buyValue} B</b></span> : null}</div>}<h4>{item.maxHp !== undefined ? "DROPS" : "DROPADO POR"}</h4><Drops drops={item.drops ?? monster?.drops ?? []} /></aside>; }
