import { useMemo, useState } from "react";
import { itemDefinitions, type GameSnapshot, type ItemId } from "@onepiece/shared";

const categories = ["all", "material", "consumable", "equipment", "fruit", "misc"] as const;
const label: Record<(typeof categories)[number], string> = { all: "Todos", material: "Materiais", consumable: "Consumíveis", equipment: "Equipamentos", fruit: "Akuma no Mi", misc: "Outros" };
const asset = (id: ItemId) => `/${itemDefinitions[id]?.icon ?? ""}`;
export function DepositPanel({ snapshot, onIntent }: { snapshot?: GameSnapshot; onIntent: (intent: unknown) => void }): JSX.Element {
  const [query, setQuery] = useState(["", ""]); const [category, setCategory] = useState<(typeof categories)[number]>("all"); const [selected, setSelected] = useState<Set<string>>(() => new Set()); const [transfer, setTransfer] = useState<{ side: 0 | 1; itemId: ItemId; max: number } | null>(null);
  const stacks = [snapshot?.player.inventory ?? [], snapshot?.player.storage ?? []] as const;
  const list = (side: 0 | 1) => stacks[side].filter((stack) => { const definition = itemDefinitions[stack.itemId]; return definition && (category === "all" || definition.category === category) && definition.displayName.toLowerCase().includes(query[side].toLowerCase()); });
  const request = (side: 0 | 1, itemId: ItemId, quantity: number) => { onIntent({ type: side === 0 ? "depositItem" : "withdrawItem", itemId, quantity }); setTransfer(null); };
  const moveSelected = (side: 0 | 1) => list(side).filter((stack) => selected.has(`${side}:${stack.itemId}`)).forEach((stack) => request(side, stack.itemId, stack.quantity));
  return <section className="deposit-panel"><header><div><span className="eyebrow">COFRE PESSOAL</span><h3>Depósito</h3><small>Bolsa e Depósito são ilimitados. O loot do Auto-Hunt sempre entra na Bolsa.</small></div><nav>{categories.map((value) => <button className={category === value ? "active" : ""} onClick={() => setCategory(value)} key={value}>{label[value]}</button>)}</nav></header><div className="deposit-columns">{([0, 1] as const).map((side) => <article className="deposit-column" key={side}><header><h4>{side ? "DEPÓSITO" : "BOLSA"}</h4><input value={query[side]} onChange={(event) => setQuery((current) => side ? [current[0], event.target.value] : [event.target.value, current[1]])} placeholder="Buscar item..." /><button onClick={() => moveSelected(side)}>{side ? "RETIRAR SELECIONADOS" : "DEPOSITAR SELECIONADOS"}</button></header><div className="deposit-grid">{list(side).map((stack) => { const definition = itemDefinitions[stack.itemId], key = `${side}:${stack.itemId}`; return <button className={`deposit-card ${selected.has(key) ? "selected" : ""}`} key={stack.itemId} onClick={() => setSelected((old) => { const next = new Set(old); next.has(key) ? next.delete(key) : next.add(key); return next; })} onDoubleClick={() => request(side, stack.itemId, stack.quantity)} onContextMenu={(event) => { event.preventDefault(); setTransfer({ side, itemId: stack.itemId, max: stack.quantity }); }} draggable onDragStart={(event) => event.dataTransfer.setData("application/x-deposit-item", JSON.stringify({ side, itemId: stack.itemId, quantity: stack.quantity }))}><img src={asset(stack.itemId)} alt="" /><b>{definition.displayName}</b><span>{definition.category} · {stack.quantity}×</span><small>{(definition as { rarity?: string }).rarity ?? "—"}</small></button>; })}{!list(side).length && <p className="empty-note">Nenhum item nesta área.</p>}</div></article>)}</div>{transfer && <TransferDialog transfer={transfer} name={itemDefinitions[transfer.itemId].displayName} onCancel={() => setTransfer(null)} onConfirm={(quantity) => request(transfer.side, transfer.itemId, quantity)} />}</section>;
}
function TransferDialog({ transfer, name, onCancel, onConfirm }: { transfer: { side: 0 | 1; itemId: ItemId; max: number }; name: string; onCancel: () => void; onConfirm: (quantity: number) => void }): JSX.Element { const [quantity, setQuantity] = useState(transfer.max); return <div className="deposit-dialog"><div><h3>{transfer.side ? "Retirar para Bolsa" : "Enviar ao Depósito"}</h3><b>{name}</b><label>Quantidade<input type="number" min="1" max={transfer.max} value={quantity} onChange={(event) => setQuantity(Math.max(1, Math.min(transfer.max, Number(event.target.value))))} /></label><nav><button onClick={() => setQuantity(Math.max(1, Math.floor(transfer.max / 2)))}>METADE</button><button onClick={() => setQuantity(transfer.max)}>TUDO</button></nav><footer><button onClick={onCancel}>CANCELAR</button><button onClick={() => onConfirm(quantity)}>CONFIRMAR</button></footer></div></div>; }
