import { useMemo, useState } from "react";
import { type GameSnapshot } from "@onepiece/shared";
const portrait = (enemyId: string) => enemyId === "enemy_buffalo" ? "/enemies/buffalo/idle/down/idle_down_01.png" : "/Monsters/Alvida/Idle/Frente/1.png";
const pct = (value: number) => `${(value / 100).toLocaleString("pt-BR", { maximumFractionDigits: 2 })}%`;
export function HuntCenter({ snapshot, onIntent, onClose }: { snapshot?: GameSnapshot; onIntent: (intent: unknown) => void; onClose: () => void }): JSX.Element {
  const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(null); const catalog = snapshot?.contentCatalog.public; const hunts = useMemo(() => (catalog?.hunts ?? []).filter((hunt) => { const enemy = catalog?.enemies.find((entry) => entry.id === hunt.mainEnemyId); return `${hunt.displayName} ${enemy?.displayName ?? ""}`.toLowerCase().includes(query.toLowerCase()); }), [catalog, query]); const selected = catalog?.hunts.find((hunt) => hunt.id === selectedId) ?? null; const active = snapshot?.huntAnalyzer.status === "ACTIVE" ? snapshot.huntAnalyzer.huntId : null;
  if (!catalog) return <p className="empty-note">Carregando Hunts…</p>;
  return <section className="hunt-center"><header><div><span className="eyebrow">ÁREAS DE FARM</span><h3>Hunts</h3><p>Escolha uma região para caçar.</p></div>{active && <button className="hunt-return" onClick={() => { onIntent({ type: "leaveHunt" }); onClose(); }}>RETORNAR AO NAVIO</button>}</header><input className="hunt-search" autoFocus placeholder="Buscar Hunt ou inimigo..." value={query} onChange={(event) => setQuery(event.target.value)} /><div className="hunt-center-grid">{hunts.map((hunt) => { const enemy = catalog.enemies.find((entry) => entry.id === hunt.mainEnemyId); const here = active === hunt.id; return <article key={hunt.id} className={here ? "active" : ""}><img src={portrait(hunt.mainEnemyId)} alt="" /><span>{here ? "VOCÊ ESTÁ AQUI" : "DISPONÍVEL"}</span><h4>{hunt.displayName}</h4><p>Inimigo principal: <b>{enemy?.displayName ?? "—"}</b></p><small>Lv. {hunt.recommendedLevelMin}–{hunt.recommendedLevelMax} · Dificuldade {hunt.difficulty}</small><footer><button onClick={() => setSelectedId(hunt.id)}>DETALHES</button><button className="primary" onClick={() => { onIntent({ type: "enterHunt", huntId: hunt.id }); onClose(); }}>{here ? "VOLTAR À HUNT" : "ENTRAR NA HUNT"}</button></footer></article>; })}</div>{selected && <HuntDetails hunt={selected} snapshot={snapshot} onBack={() => setSelectedId(null)} />}</section>;
}
function HuntDetails({ hunt, snapshot, onBack }: { hunt: NonNullable<GameSnapshot["contentCatalog"]["public"]>["hunts"][number]; snapshot?: GameSnapshot; onBack: () => void }): JSX.Element { const catalog = snapshot!.contentCatalog.public; const enemy = catalog.enemies.find((entry) => entry.id === hunt.mainEnemyId); const byId = new Map([...catalog.items, ...catalog.fruits].map((entry) => [entry.id, entry])); return <aside className="hunt-detail"><button onClick={onBack}>← VOLTAR</button><img src={portrait(hunt.mainEnemyId)} alt="" /><h3>{hunt.displayName}</h3><p>{hunt.description}</p><div className="hunt-detail-stats"><span>Nível <b>{hunt.recommendedLevelMin}–{hunt.recommendedLevelMax}</b></span><span>HP <b>{enemy?.maxHp ?? "—"}</b></span><span>XP <b>{enemy?.xpReward ?? "—"}</b></span><span>Berries <b>{enemy?.berriesReward ?? "—"}</b></span></div><h4>MONSTROS</h4><p>{enemy?.displayName ?? "—"}</p><h4>DROPS</h4><ul>{enemy?.drops.map((drop) => <li key={drop.itemId}><b>{byId.get(drop.itemId)?.displayName ?? drop.itemId}</b><span>{pct(drop.chanceBps)} · ×{drop.minQuantity}{drop.maxQuantity !== drop.minQuantity ? `–${drop.maxQuantity}` : ""}</span></li>) ?? <li>—</li>}</ul></aside>; }
