import type { Direction, EnemyState, NpcState, PlayerState } from "@onepiece/shared";
export interface AnimationFrame { texture: string; flipX: boolean; key: string; }
const tedState = (state: PlayerState): "idle" | "walk" | "attack" | "death" => state === "WALK" ? "walk" : state === "ATTACK" ? "attack" : state === "DEAD" ? "death" : "idle";
const alvidaDirection = (direction: Direction): "Frente" | "Costa" | "Lado" => direction === "up" ? "Costa" : direction === "down" ? "Frente" : "Lado";
/** Returns through the intermediate poses instead of snapping last frame back to first. */
const loopFrame = (frames: number, now: number, fps: number, pingPong = false): number => { const sequence = pingPong && frames > 2 ? [...Array(frames).keys(), ...Array.from({ length: frames - 2 }, (_, index) => frames - 2 - index)] : [...Array(frames).keys()]; return sequence[Math.floor(now / (1000 / fps)) % sequence.length] + 1; };
/** Ted only has a frontal walk set; Costa/Lado are the approved directional assets. */
export function tedFrame(state: PlayerState, direction: Direction, now: number): AnimationFrame { const source = tedState(state); const flipX = direction === "left"; if (source === "idle") { if (direction === "up") { const frame = loopFrame(5, now, 6); return { texture: `ted_idle_Costa_${frame}`, flipX: false, key: "ted_idle_up" }; } if (direction === "left" || direction === "right") { const frame = loopFrame(5, now, 6); return { texture: `ted_idle_Lado_${frame}`, flipX, key: "ted_idle_side" }; } const frame = loopFrame(6, now, 6); return { texture: `ted_idle_${frame}`, flipX: false, key: "ted_idle_down" }; } if (source === "walk" && direction !== "down") { const frame = loopFrame(5, now, 7); const view = direction === "up" ? "Costa" : "Lado"; return { texture: `ted_idle_${view}_${frame}`, flipX, key: `ted_walk_${direction === "up" ? "up" : "side"}` }; } const frame = loopFrame(6, now, source === "attack" ? 7 : source === "walk" ? 7 : 5); return { texture: `ted_${source}_${frame}`, flipX, key: `ted_${source}_${direction}` }; }
export function oldDrunkFrame(state: NpcState, now: number): AnimationFrame { const source = state.toLowerCase() as "idle" | "drink" | "sway" | "interact" | "heal"; const counts = { idle: 4, drink: 6, sway: 4, interact: 4, heal: 5 } as const; const fps = source === "idle" ? 4 : source === "drink" || source === "heal" ? 6 : source === "sway" ? 3 : 5; const frame = Math.floor(now / (1000 / fps)) % counts[source] + 1; return { texture: `old_drunk_seated_${source}_${frame}`, flipX: false, key: `old_drunk_${source}` }; }
export function alvidaFrame(state: EnemyState, direction: Direction, now: number): AnimationFrame { if (state === "ATTACK") { const frame = loopFrame(3, now, 7); return { texture: `alvida_Attack_${frame}`, flipX: direction === "left", key: `alvida_attack_${direction}` }; } const source = state === "CHASE" ? "Walking" : "Idle"; const frame = loopFrame(4, now, source === "Walking" ? 10 : 7, true); return { texture: `alvida_${source}_${alvidaDirection(direction)}_${frame}`, flipX: direction === "left", key: `alvida_${source.toLowerCase()}_${direction}` }; }
export function buffaloFrame(state: EnemyState, direction: Direction, now: number): AnimationFrame { const side = direction === "left" || direction === "right"; if (state === "ATTACK") { const frame = loopFrame(6, now, 7); return { texture: `buffalo_attack_${frame}`, flipX: direction === "left", key: "buffalo_attack" }; } const walking = state === "CHASE"; const frame = loopFrame(walking ? 5 : 4, now, walking ? 8 : 4, true); const view = direction === "up" ? "up" : side ? "side" : "down"; return { texture: `buffalo_${walking ? "walk" : "idle"}_${view}_${frame}`, flipX: direction === "left", key: `buffalo_${walking ? "walk" : "idle"}_${view}` }; }
